### ISSUE TITLE
Always same targets

### ISSUE THREAD

**Issue by YuriyChmil** [Arriven/db1000n#132] opened 2022-03-05 11:24 UTC
Hey. I am running this image on AWS via terraformm.
From logs, I see that it attack only one IP with different port
is it ok?
`
Attacking http://82.202.190.240:8010
[INFO]  2022/03/05 11:22:21 [INFO] Attacking http://82.202.190.240:443
[INFO]  2022/03/05 11:22:21 [INFO] Attacking http://82.202.190.240:80
[INFO]  2022/03/05 11:22:22 [INFO] Attacking http://82.202.190.240:443
[INFO]  2022/03/05 11:22:22 [INFO] Attacking http://82.202.190.240:8010
[INFO]  2022/03/05 11:22:22 [INFO] Attacking http://82.202.190.240:80
[INFO]  2022/03/05 11:22:23 [INFO] Attacking http://82.202.190.240:443

`

**Comment by vgoncharenko** [comment] 2022-03-05 11:47
same on my aws

**Comment by pavliukvlad** [comment] 2022-03-05 12:09
The same

**Comment by iamtodor** [comment] 2022-03-05 12:16
same here

**Comment by Arriven** [comment] 2022-03-05 12:22
I'll get back to take a closer look at this in couple minutes but for now can somebody check it against the config present [here](https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json) and [here](https://github.com/Arriven/db1000n/blob/main/src/config/defaultconfig.go)?

**Comment by iamtodor** [comment] 2022-03-05 12:27
might relates to https://github.com/Arriven/db1000n/issues/121

**Comment by vgoncharenko** [comment] 2022-03-05 12:36
just about a minute ago it got fixed. Many new targets started showing up:

[INFO]  2022/03/05 12:32:58 [INFO] Attacking http://82.202.190.240:80
[INFO]  2022/03/05 12:32:58 [INFO] Attacking http://victori.gtrklnr.ru/
[INFO]  2022/03/05 12:32:58 [INFO] Attacking http://victori.gtrklnr.ru/
[INFO]  2022/03/05 12:32:58 [INFO] Attacking http://193.228.161.83:80
[INFO]  2022/03/05 12:32:58 [INFO] Attacking https://193.228.161.83:443
[INFO]  2022/03/05 12:32:58 [INFO] Attacking https://193.228.161.83:443
[INFO]  2022/03/05 12:32:58 [INFO] Attacking http://193.228.161.83:80
[INFO]  2022/03/05 12:32:58 [INFO] Attacking https://193.228.161.83:443
[INFO]  2022/03/05 12:32:58 [INFO] Атака проводиться успішно! Руський воєнний корабль іди нахуй!
[INFO]  2022/03/05 12:32:58 [INFO] Attack is successful! Russian warship, go fuck yourself!
[INFO]  2022/03/05 12:32:58 [INFO] The app is generating approximately 8170773 bytes per second
[INFO]  2022/03/05 12:32:58 [INFO] Attacking http://news.gtrklnr.ru/
[INFO]  2022/03/05 12:32:58 [INFO] Attacking http://193.228.161.83:80
[INFO]  2022/03/05 12:32:58 [INFO] Attacking http://victori.gtrklnr.ru/
[INFO]  2022/03/05 12:32:58 [INFO] Attacking http://victori.gtrklnr.ru/
[INFO]  2022/03/05 12:32:58 [INFO] Attacking https://193.228.161.83:443
[INFO]  2022/03/05 12:32:58 [INFO] Attacking http://193.228.161.83:80
[INFO]  2022/03/05 12:32:58 [INFO] Attacking http://victori.gtrklnr.ru/

**Comment by pavliukvlad** [comment] 2022-03-05 12:43
I can confirm as well that there are a lot of new targets now.

**Comment by vgoncharenko** [comment] 2022-03-05 12:46
But all metrics went down dramatically as well:
throughput went down from 470Mb/min to 200kb/min:
And everything, CPU, packets.
<img width="1122" alt="Screen Shot 2022-03-05 at 6 43 59 AM" src="https://user-images.githubusercontent.com/10031428/156883590-1aa99bf7-67fb-4b46-8146-b628c9c8cd0b.png">

**Comment by pavliukvlad** [comment] 2022-03-05 12:48
I also noticed that 
![image](https://user-images.githubusercontent.com/26973559/156883766-582a9f2f-e6cb-422c-add0-1f0e5adb1de8.png)

**Comment by iamtodor** [comment] 2022-03-05 12:50
can confirm the same. new targets have arrived
@Arriven could you please shed some light on the issue? have you changed something? what was wrong or what was fixed?

**Comment by vgoncharenko** [comment] 2022-03-05 13:00
Looks like targets very week but still reachable:

Target 1:
PING 193.228.161.83 (193.228.161.83) 56(84) bytes of data.
64 bytes from 193.228.161.83: icmp_seq=1 ttl=34 time=133 ms
64 bytes from 193.228.161.83: icmp_seq=3 ttl=34 time=133 ms
64 bytes from 193.228.161.83: icmp_seq=4 ttl=34 time=133 ms
64 bytes from 193.228.161.83: icmp_seq=5 ttl=34 time=133 ms
64 bytes from 193.228.161.83: icmp_seq=8 ttl=34 time=133 ms
^C
--- 193.228.161.83 ping statistics ---
8 packets transmitted, 5 received, 37% packet loss, time 7058ms
rtt min/avg/max/mdev = 133.146/133.297/133.760/0.233 ms

sudo nmap -sS -T2 -p 443 and 80 193.228.161.83:

Host is up (0.13s latency).
PORT    STATE SERVICE
443/tcp open  https
80/tcp filtered http

Nmap done: 1 IP address (1 host up) scanned in 3.85 seconds

Target 2:
PING victori.gtrklnr.ru (193.228.161.83) 56(84) bytes of data.
64 bytes from 193.228.161.83 (193.228.161.83): icmp_seq=5 ttl=34 time=133 ms
64 bytes from 193.228.161.83 (193.228.161.83): icmp_seq=6 ttl=34 time=133 ms
64 bytes from 193.228.161.83 (193.228.161.83): icmp_seq=11 ttl=34 time=135 ms
64 bytes from 193.228.161.83 (193.228.161.83): icmp_seq=12 ttl=34 time=133 ms
64 bytes from 193.228.161.83 (193.228.161.83): icmp_seq=19 ttl=34 time=133 ms
64 bytes from 193.228.161.83 (193.228.161.83): icmp_seq=21 ttl=34 time=133 ms
64 bytes from 193.228.161.83 (193.228.161.83): icmp_seq=22 ttl=34 time=133 ms

curl -I -L http://victori.gtrklnr.ru/ -v
*   Trying 193.228.161.83:80...
* Connected to victori.gtrklnr.ru (193.228.161.83) port 80 (#0)
> HEAD / HTTP/1.1
> Host: victori.gtrklnr.ru
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK

**Comment by dmy3tka** [comment] 2022-03-05 13:38
Why CPU utilisation is dropped so drastically, do we fix resource leakage in code or rps is so week now and things broke?

**Comment by Arriven** [comment] 2022-03-06 10:00
https://github.com/Arriven/db1000n/issues/136#issuecomment-1059756173

**Comment by iamtodor** [comment] 2022-03-06 13:14
@Arriven @Amet13 I think we can close this issue for now. What do you think?

**Comment by dmy3tka** [comment] 2022-03-06 18:43
We can close the issue. We don't have issue with targets update.

**Closed** 2022-03-07 06:47 UTC
